//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPence.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPence.Shared.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format..
        /// </summary>
        public static string ER_INVALID_AMOUNT {
            get {
                return ResourceManager.GetString("ER_INVALID_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some problem occurred in the application. Please try later..
        /// </summary>
        public static string ERR_APP_ERROR {
            get {
                return ResourceManager.GetString("ERR_APP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant select user..
        /// </summary>
        public static string ERR_CANT_SELECT_USER {
            get {
                return ResourceManager.GetString("ERR_CANT_SELECT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 255 chars permitted..
        /// </summary>
        public static string ERR_DESCRIPTION_TOO_LONG {
            get {
                return ResourceManager.GetString("ERR_DESCRIPTION_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password did not match please try again..
        /// </summary>
        public static string ERR_FAILED_LOGIN_MESSAGE {
            get {
                return ResourceManager.GetString("ERR_FAILED_LOGIN_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the transactions..
        /// </summary>
        public static string ERR_FAILED_TO_DELETE_TRANS {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_DELETE_TRANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the user list.
        /// </summary>
        public static string ERR_FAILED_TO_GET_USERS {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_GET_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the transactions..
        /// </summary>
        public static string ERR_FAILED_TO_LOAD_TRNS {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_LOAD_TRNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the users..
        /// </summary>
        public static string ERR_FAILED_TO_LOAD_USERS {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_LOAD_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the transaction..
        /// </summary>
        public static string ERR_FAILED_TO_SAVE_TRANS {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_SAVE_TRANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the user..
        /// </summary>
        public static string ERR_FAILED_TO_SAVE_USER {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_SAVE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date cannot be after to date..
        /// </summary>
        public static string ERR_FROM_TO_DATE {
            get {
                return ResourceManager.GetString("ERR_FROM_TO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount..
        /// </summary>
        public static string ERR_INCORRECT_AMOUNT {
            get {
                return ResourceManager.GetString("ERR_INCORRECT_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is mandatory..
        /// </summary>
        public static string ERR_MAND_AMOUNT_MESSAGE {
            get {
                return ResourceManager.GetString("ERR_MAND_AMOUNT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty..
        /// </summary>
        public static string ERR_NAME_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("ERR_NAME_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 30..
        /// </summary>
        public static string ERR_NAME_CANNOT_BE_LONG {
            get {
                return ResourceManager.GetString("ERR_NAME_CANNOT_BE_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be empty..
        /// </summary>
        public static string ERR_NEW_PASSORD_EMPTY {
            get {
                return ResourceManager.GetString("ERR_NEW_PASSORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The existing password entered is incorrect..
        /// </summary>
        public static string ERR_PASSWOR_NO_MATCH_MSG {
            get {
                return ResourceManager.GetString("ERR_PASSWOR_NO_MATCH_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reenter pwd. does not match..
        /// </summary>
        public static string ERR_PASSWORDS_MISMATCH {
            get {
                return ResourceManager.GetString("ERR_PASSWORDS_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is empty..
        /// </summary>
        public static string ERR_USERNAME_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("ERR_USERNAME_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 10..
        /// </summary>
        public static string ERR_USERNAME_CANNOT_BE_LONG {
            get {
                return ResourceManager.GetString("ERR_USERNAME_CANNOT_BE_LONG", resourceCulture);
            }
        }
    }
}
